### ISSUE TITLE
composer install fails with master

### ISSUE THREAD

**Issue by ghost** [helhum/TYPO3-Distribution#12]
after cloning the repository without any modification, composer install fails with following errors

```
$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
Registered helhum/dotenv-connector
Setting up TYPO3 Core Extension directories

Setting up TYPO3


  [TYPO3\CMS\Extbase\Object\Container\Exception\UnknownObjectException]
  Could not analyse class: "Helhum\Typo3Console\Mvc\Cli\CommandManager" maybe not loaded or no autoloader? Class Helh
  um\Typo3Console\Mvc\Cli\CommandManager does not exist



  [ReflectionException]
  Class Helhum\Typo3Console\Mvc\Cli\CommandManager does not exist


install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

```

**Comment by ghost** [comment]
for clarification: this isn't the initial composer install log, it failed too at the same stage while Setting up TYPO3. this log is from another run directly after the previos fail.

**Comment by helhum** [comment]
fixed now with https://github.com/helhum/TYPO3-Distribution/commit/47a3e332a9baefe213750fecde7e304c766d5da4 and new 8.7 branch is created

**Comment by helipus** [comment]
I fear the error was not fixed yet in the 8.1 branch which is there via composer? I have the same error there.

**Comment by helhum** [comment]
can you specify the exact commands you type and the full output of them? thanks.

**Comment by helipus** [comment]
Thank you for the quick response. Yes sure. Here it is:
```php
# composer create-project helhum/typo3-distribution test-project

Installing helhum/typo3-distribution (v8.1.0)
  - Installing helhum/typo3-distribution (v8.1.0): Loading from cache
Created project in test-project
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 95 installs, 0 updates, 0 removals
  - Installing typo3/class-alias-loader (1.0.0): Loading from cache
  - Installing typo3/cms-composer-installers (1.4.5): Loading from cache
  - Installing helhum/typo3-console-plugin (2.0.4): Loading from cache
  - Installing symfony/dotenv (v3.4.3): Loading from cache
  - Installing helhum/dotenv-connector (2.0.2): Loading from cache
  - Installing doctrine/lexer (v1.0.1): Loading from cache
  - Installing doctrine/inflector (v1.2.0): Loading from cache
  - Installing doctrine/collections (v1.4.0): Loading from cache
  - Installing doctrine/cache (v1.6.2): Loading from cache
  - Installing doctrine/annotations (v1.4.0): Loading from cache
  - Installing doctrine/common (v2.7.3): Loading from cache
  - Installing doctrine/dbal (v2.5.13): Loading from cache
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.4.2): Loading from cache
  - Installing guzzlehttp/guzzle (6.3.0): Loading from cache
  - Installing typo3fluid/fluid (2.4.0): Loading from cache
  - Installing mso/idna-convert (v1.1.0): Loading from cache
  - Installing cogpowered/finediff (0.3.1): Loading from cache
  - Installing typo3/cms-core (v8.7.9): Loading from cache
  - Installing symfony/process (v3.4.3): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.6.0): Loading from cache
  - Installing psr/log (1.0.2): Loading from cache
  - Installing symfony/debug (v3.4.3): Loading from cache
  - Installing symfony/console (v3.4.3): Loading from cache
  - Installing typo3/cms-saltedpasswords (v8.7.9): Loading from cache
  - Installing helhum/typo3-console (5.0.2): Loading from cache
  - Installing typo3/cms-scheduler (v8.7.9): Loading from cache
  - Installing symfony/finder (v3.4.3): Loading from cache
  - Installing typo3/cms-extbase (v8.7.9): Loading from cache
  - Installing typo3/cms-fluid (v8.7.9): Loading from cache
  - Installing typo3/cms-install (v8.7.9): Loading from cache
  - Installing typo3/cms-extensionmanager (v8.7.9): Loading from cache
  - Installing typo3/cms-backend (v8.7.9): Loading from cache
  - Installing doctrine/instantiator (1.0.5): Loading from cache
  - Installing symfony/yaml (v3.4.3): Loading from cache
  - Installing swiftmailer/swiftmailer (v5.4.8): Loading from cache
  - Installing typo3/cms-sv (v8.7.9): Loading from cache
  - Installing typo3/cms-recordlist (v8.7.9): Loading from cache
  - Installing typo3/cms-lang (v8.7.9): Loading from cache
  - Installing typo3/cms-frontend (v8.7.9): Loading from cache
  - Installing typo3/cms-filelist (v8.7.9): Loading from cache
  - Installing typo3/cms-cshmanual (v8.7.9): Loading from cache
  - Installing helhum/typo3-composer-setup (v0.5.1): Loading from cache
  - Installing helhum/typo3-secure-web (v0.2.7): Loading from cache
  - Installing typo3/cms-belog (v8.7.9): Loading from cache
  - Installing typo3/cms-beuser (v8.7.9): Loading from cache
  - Installing typo3/cms-context-help (v8.7.9): Loading from cache
  - Installing typo3/cms-fluid-styled-content (v8.7.9): Loading from cache
  - Installing typo3/cms-impexp (v8.7.9): Loading from cache
  - Installing typo3/cms-info (v8.7.9): Loading from cache
  - Installing typo3/cms-info-pagetsconfig (v8.7.9): Loading from cache
  - Installing typo3/cms-lowlevel (v8.7.9): Loading from cache
  - Installing typo3/cms-reports (v8.7.9): Loading from cache
  - Installing typo3/cms-rte-ckeditor (v8.7.9): Loading from cache
  - Installing typo3/cms-setup (v8.7.9): Loading from cache
  - Installing typo3/cms-tstemplate (v8.7.9): Loading from cache
  - Installing typo3/cms-viewpage (v8.7.9): Loading from cache
  - Installing helhum/typo3-error-handling (dev-master): Symlinking from packages/typo3-error-handling
  - Installing helhum/site-package (dev-master): Symlinking from packages/helhum_site_package
  - Installing typo3-console/php-server-command (0.1.3): Loading from cache
  - Installing typo3-console/composer-auto-setup (0.3.5): Loading from cache
  - Installing helhum/config-loader (0.5.3): Loading from cache
  - Installing helhum/typo3-config-handling (v0.3.3): Loading from cache
  - Installing mikey179/vfsstream (v1.6.5): Loading from cache
  - Installing sebastian/version (2.0.1): Loading from cache
  - Installing sebastian/resource-operations (1.0.0): Loading from cache
  - Installing sebastian/recursion-context (3.0.0): Loading from cache
  - Installing sebastian/object-reflector (1.1.1): Loading from cache
  - Installing sebastian/object-enumerator (3.0.3): Loading from cache
  - Installing sebastian/global-state (2.0.0): Loading from cache
  - Installing sebastian/exporter (3.1.0): Loading from cache
  - Installing sebastian/environment (3.1.0): Loading from cache
  - Installing sebastian/diff (2.0.1): Loading from cache
  - Installing sebastian/comparator (2.1.1): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/phpunit-mock-objects (5.0.6): Loading from cache
  - Installing phpunit/php-timer (1.0.9): Loading from cache
  - Installing phpunit/php-file-iterator (1.4.5): Loading from cache
  - Installing theseer/tokenizer (1.1.0): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
  - Installing phpunit/php-token-stream (2.0.2): Loading from cache
  - Installing phpunit/php-code-coverage (5.3.0): Loading from cache
  - Installing webmozart/assert (1.2.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0.1): Loading from cache
  - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (4.2.0): Loading from cache
  - Installing phpspec/prophecy (1.7.3): Loading from cache
  - Installing phar-io/version (1.0.1): Loading from cache
  - Installing phar-io/manifest (1.0.1): Loading from cache
  - Installing myclabs/deep-copy (1.7.0): Loading from cache
  - Installing phpunit/phpunit (6.5.5): Loading from cache
  - Installing typo3/testing-framework (2.0.2): Loading from cache
symfony/console suggests installing symfony/event-dispatcher ()
symfony/console suggests installing symfony/lock ()
typo3/cms-saltedpasswords suggests installing typo3/cms-rsaauth (*)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.5.5)
phpunit/phpunit suggests installing phpunit/php-invoker (^1.1)
phpunit/phpunit suggests installing ext-xdebug (*)
typo3/testing-framework suggests installing codeception/codeception (^2.2)
typo3/testing-framework suggests installing se/selenium-server-standalone (~2.53)
typo3/testing-framework suggests installing typo3/cms-styleguide (~8.0.8)
Writing lock file
Generating autoload files
Registered helhum/dotenv-connector
The class alias map file "Migrations/Code/ClassAliasMap.php" configured in package "typo3/cms-reports" was not found!
Generating  class alias map file
Inserting class alias loader into main autoload.php file

Setting up TYPO3


  [ TypeError ]
  Argument 6 passed to Symfony\Component\Process\Process::__construct() must be of the type array, null given, called in /home/www/dfki_taskforce/test-project/vendor/symfony/process/ProcessBuilder.php on line 266


Exception trace:
#0 ()
   phar:///home/bin/composer.phar/vendor/symfony/process/Process.php:137
#1 Symfony\Component\Process\Process::__construct()
   vendor/symfony/process/ProcessBuilder.php:266
#2 Symfony\Component\Process\ProcessBuilder::getProcess()
   vendor/helhum/typo3-console/Classes/Mvc/Cli/CommandDispatcher.php:196
#3 Helhum\Typo3Console\Mvc\Cli\CommandDispatcher::executeCommand()
   vendor/helhum/typo3-console/Classes/Install/CliSetupRequestHandler.php:110
#4 Helhum\Typo3Console\Install\CliSetupRequestHandler::setup()
   vendor/typo3-console/composer-auto-setup/src/Composer/InstallerScript/SetupTypo3.php:101
#5 Typo3Console\ComposerAutoSetup\Composer\InstallerScript\SetupTypo3::run()
   vendor/typo3/cms-composer-installers/src/Plugin/Core/ScriptDispatcher.php:88
#6 TYPO3\CMS\Composer\Plugin\Core\ScriptDispatcher::executeScripts()
   vendor/typo3/cms-composer-installers/src/Plugin/PluginImplementation.php:93
#7 TYPO3\CMS\Composer\Plugin\PluginImplementation::postAutoloadDump()
   vendor/typo3/cms-composer-installers/src/Installer/Plugin.php:125
#8 TYPO3\CMS\Composer\Installer\Plugin::listen()
#9 call_user_func()
   phar:///home/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:171
#10 Composer\EventDispatcher\EventDispatcher::doDispatch()
   phar:///home/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:96
#11 Composer\EventDispatcher\EventDispatcher::dispatchScript()
   phar:///home/bin/composer.phar/src/Composer/Autoload/AutoloadGenerator.php:312
#12 Composer\Autoload\AutoloadGenerator::dump()
   phar:///home/bin/composer.phar/src/Composer/Installer.php:302
#13 Composer\Installer::run()
   phar:///home/bin/composer.phar/src/Composer/Command/CreateProjectCommand.php:191
#14 Composer\Command\CreateProjectCommand::installProject()
   phar:///home/bin/composer.phar/src/Composer/Command/CreateProjectCommand.php:143
#15 Composer\Command\CreateProjectCommand::execute()
   phar:///home/bin/composer.phar/vendor/symfony/console/Command/Command.php:242
#16 Symfony\Component\Console\Command\Command::run()
   phar:///home/bin/composer.phar/vendor/symfony/console/Application.php:842
#17 Symfony\Component\Console\Application::doRunCommand()
   phar:///home/bin/composer.phar/vendor/symfony/console/Application.php:193
#18 Symfony\Component\Console\Application::doRun()
   phar:///home/bin/composer.phar/src/Composer/Console/Application.php:251
#19 Composer\Console\Application::doRun()
   phar:///home/bin/composer.phar/vendor/symfony/console/Application.php:117
#20 Symfony\Component\Console\Application::run()
   phar:///home/bin/composer.phar/src/Composer/Console/Application.php:100
#21 Composer\Console\Application::run()
   phar:///home/bin/composer.phar/bin/composer:58
#22 require()
   /home/bin/composer.phar:24
```

Composer runs with PHP 7.0.
```bash
# php -v
PHP 7.0.21 (cli) (built: Jul 17 2017 13:03:30) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v10.0.0 (), Copyright (c) 2002-2017, by ionCube Ltd.
```

I get the same error with v8.1.0, 8.7.x-dev and dev-master from https://packagist.org.

**Comment by helhum** [comment]
Ah, thanks. That is a totally different error.

```
#0 ()
   phar:///home/bin/composer.phar/vendor/symfony/process/Process.php:137
```

Hm ok, what Composer version are you using?

**Comment by helipus** [comment]
```bash
 # composer --version
Composer version 1.6.2 2018-01-05 15:28:41
```

**Comment by helhum** [comment]
thanks. can you manually patch typo3-console with this: https://github.com/TYPO3-Console/TYPO3-Console/commit/f80e5852ee07b7b363c1e7a8c4030ac74e2326e1.diff

and tell if it helps?

Unfortunately I cannot reproduce this, but the error message is pretty clear, so the fix should help

**Comment by helhum** [comment]
https://github.com/TYPO3-Console/TYPO3-Console/pull/659/commits/f80e5852ee07b7b363c1e7a8c4030ac74e2326e1

**Comment by helipus** [comment]
I tried to add the patch via composer. But somehow there must be a mistake because I don't see that the patch is installed. Did I use the correct "vendor/package" string?
Here is your composer.json added with your patch file:
```php
{
    "repositories": [
        { "type": "path", "url": "packages/*" },
        { "type": "composer", "url": "https://composer.typo3.org/" }
    ],
    "name": "helhum/typo3-distribution",
    "description" : "TYPO3 CMS Distribution with console and .env support",
    "license": "GPL-2.0+",
    "require": {
        "helhum/typo3-config-handling": "^0.3.1",
        "helhum/typo3-secure-web": "^0.2.7",
        "typo3-console/composer-auto-setup": "^0.3.5",

        "roave/security-advisories": "dev-master",

        "typo3/cms-belog": "^8.7.9",
        "typo3/cms-beuser": "^8.7.9",
        "typo3/cms-context-help": "^8.7.9",
        "typo3/cms-fluid-styled-content": "^8.7.9",
        "typo3/cms-impexp": "^8.7.9",
        "typo3/cms-info": "^8.7.9",
        "typo3/cms-info-pagetsconfig": "^8.7.9",
        "typo3/cms-lowlevel": "^8.7.9",
        "typo3/cms-reports": "^8.7.9",
        "typo3/cms-rte-ckeditor": "^8.7.9",
        "typo3/cms-setup": "^8.7.9",
        "typo3/cms-tstemplate": "^8.7.9",
        "typo3/cms-viewpage": "^8.7.9",

        "helhum/typo3-error-handling": "@dev",
        "helhum/site-package": "@dev"
    },
    "require-dev": {
        "helhum/dotenv-connector": "^2.0",
        "typo3/testing-framework": "^1.2.2 || ^2.0.1",
        "typo3-console/php-server-command": "^0.1.3"
    },
    "extra": {
        "helhum/typo3-config-handling": {
            "ext-config": "conf/config.extension.yml"
        },
        "typo3/cms": {
            "root-dir": "private",
            "web-dir": "public"
        },
        "patches": {
           "typo3-console/composer-auto-setup": {
             "[BUGFIX] Add options to ProcessBuilder, commit f80e5852ee07b7b363c1e7a8c4030ac74e2326e1": "https://github.com/TYPO3-Console/TYPO3-Console/commit/f80e5852ee07b7b363c1e7a8c4030ac74e2326e1.diff"
           }
        }            
    }
}
```

**Comment by helhum** [comment]
this is a patch for `helhum/typo3-console` not `typo3-console/composer-auto-setup`

**Comment by helipus** [comment]
hm. okay I did try these also before. Didn't change anything:
Here is your composer.json:
```php
{
    "repositories": [
        { "type": "path", "url": "packages/*" },
        { "type": "composer", "url": "https://composer.typo3.org/" }
    ],
    "name": "helhum/typo3-distribution",
    "description" : "TYPO3 CMS Distribution with console and .env support",
    "license": "GPL-2.0+",
    "require": {
        "helhum/typo3-config-handling": "^0.3.1",
        "helhum/typo3-secure-web": "^0.2.7",
        "typo3-console/composer-auto-setup": "^0.3.5",

        "roave/security-advisories": "dev-master",

        "typo3/cms-belog": "^8.7.9",
        "typo3/cms-beuser": "^8.7.9",
        "typo3/cms-context-help": "^8.7.9",
        "typo3/cms-fluid-styled-content": "^8.7.9",
        "typo3/cms-impexp": "^8.7.9",
        "typo3/cms-info": "^8.7.9",
        "typo3/cms-info-pagetsconfig": "^8.7.9",
        "typo3/cms-lowlevel": "^8.7.9",
        "typo3/cms-reports": "^8.7.9",
        "typo3/cms-rte-ckeditor": "^8.7.9",
        "typo3/cms-setup": "^8.7.9",
        "typo3/cms-tstemplate": "^8.7.9",
        "typo3/cms-viewpage": "^8.7.9",

        "helhum/typo3-error-handling": "@dev",
        "helhum/site-package": "@dev"
    },
    "require-dev": {
        "helhum/dotenv-connector": "^2.0",
        "typo3/testing-framework": "^1.2.2 || ^2.0.1",
        "typo3-console/php-server-command": "^0.1.3"
    },
    "extra": {
        "helhum/typo3-config-handling": {
            "ext-config": "conf/config.extension.yml"
        },
        "typo3/cms": {
            "root-dir": "private",
            "web-dir": "public"
        },
        "patches": {           
           "helhum/typo3-console": {
             "[BUGFIX] Add options to ProcessBuilder, commit f80e5852ee07b7b363c1e7a8c4030ac74e2326e1": "https://github.com/TYPO3-Console/TYPO3-Console/commit/f80e5852ee07b7b363c1e7a8c4030ac74e2326e1.diff"
           }
        }            
    }
}
```


Here the output:
```bash
 # composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating autoload files
Registered helhum/dotenv-connector
The class alias map file "Migrations/Code/ClassAliasMap.php" configured in package "typo3/cms-reports" was not found!
Generating  class alias map file
Inserting class alias loader into main autoload.php file

Setting up TYPO3


  [ TypeError ]
  Argument 6 passed to Symfony\Component\Process\Process::__construct() must be of the type array, null given, called in /home/www/dfki_taskforce/test1/vendor/symfony/process/ProcessBuilder.php on line 266


Exception trace:
#0 ()
   phar:///home/bin/composer.phar/vendor/symfony/process/Process.php:137
#1 Symfony\Component\Process\Process::__construct()
   vendor/symfony/process/ProcessBuilder.php:266
#2 Symfony\Component\Process\ProcessBuilder::getProcess()
   vendor/helhum/typo3-console/Classes/Mvc/Cli/CommandDispatcher.php:196
#3 Helhum\Typo3Console\Mvc\Cli\CommandDispatcher::executeCommand()
   vendor/helhum/typo3-console/Classes/Install/CliSetupRequestHandler.php:110
#4 Helhum\Typo3Console\Install\CliSetupRequestHandler::setup()
   vendor/typo3-console/composer-auto-setup/src/Composer/InstallerScript/SetupTypo3.php:101
#5 Typo3Console\ComposerAutoSetup\Composer\InstallerScript\SetupTypo3::run()
   vendor/typo3/cms-composer-installers/src/Plugin/Core/ScriptDispatcher.php:88
#6 TYPO3\CMS\Composer\Plugin\Core\ScriptDispatcher::executeScripts()
   vendor/typo3/cms-composer-installers/src/Plugin/PluginImplementation.php:93
#7 TYPO3\CMS\Composer\Plugin\PluginImplementation::postAutoloadDump()
   vendor/typo3/cms-composer-installers/src/Installer/Plugin.php:125
#8 TYPO3\CMS\Composer\Installer\Plugin::listen()
#9 call_user_func()
   phar:///home/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:171
#10 Composer\EventDispatcher\EventDispatcher::doDispatch()
   phar:///home/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:96
#11 Composer\EventDispatcher\EventDispatcher::dispatchScript()
   phar:///home/bin/composer.phar/src/Composer/Autoload/AutoloadGenerator.php:312
#12 Composer\Autoload\AutoloadGenerator::dump()
   phar:///home/bin/composer.phar/src/Composer/Installer.php:302
#13 Composer\Installer::run()
   phar:///home/bin/composer.phar/src/Composer/Command/UpdateCommand.php:161
#14 Composer\Command\UpdateCommand::execute()
   phar:///home/bin/composer.phar/vendor/symfony/console/Command/Command.php:242
#15 Symfony\Component\Console\Command\Command::run()
   phar:///home/bin/composer.phar/vendor/symfony/console/Application.php:842
#16 Symfony\Component\Console\Application::doRunCommand()
   phar:///home/bin/composer.phar/vendor/symfony/console/Application.php:193
#17 Symfony\Component\Console\Application::doRun()
   phar:///home/bin/composer.phar/src/Composer/Console/Application.php:251
#18 Composer\Console\Application::doRun()
   phar:///home/bin/composer.phar/vendor/symfony/console/Application.php:117
#19 Symfony\Component\Console\Application::run()
   phar:///home/bin/composer.phar/src/Composer/Console/Application.php:100
#20 Composer\Console\Application::run()
   phar:///home/bin/composer.phar/bin/composer:58
#21 require()
   /home/bin/composer.phar:24
```
Thank you so much for your support!

**Comment by helhum** [comment]
uhm, if you don't inlcude the patches plugin, then nothing will get patched ;)

**Comment by helhum** [comment]
`composer require cweagans/composer-patches`

**Comment by helhum** [comment]
or just manually change the few lines

**Comment by helipus** [comment]
Ok sorry that helped! I thought this was basic functionality for composer. 
The patch was installed now succesfully, but sadly the next error was displayed:
```bash
 composer update
Gathering patches for root package.
Removing package helhum/typo3-console so that it can be re-installed and re-patched.
  - Removing helhum/typo3-console (5.0.2)
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
Gathering patches for root package.
Gathering patches for dependencies. This might take a minute.
  - Installing helhum/typo3-console (5.0.2): Loading from cache
  - Applying patches for helhum/typo3-console
    https://github.com/TYPO3-Console/TYPO3-Console/commit/f80e5852ee07b7b363c1e7a8c4030ac74e2326e1.diff ([BUGFIX] Add options to ProcessBuilder, commit f80e5852ee07b7b363c1e7a8c4030ac74e2326e1)

Writing lock file
Generating autoload files
Registered helhum/dotenv-connector
The class alias map file "Migrations/Code/ClassAliasMap.php" configured in package "typo3/cms-reports" was not found!
Generating  class alias map file
Inserting class alias loader into main autoload.php file

Setting up TYPO3


  [ Error ]
  Call to undefined method Symfony\Component\Process\Process::inheritEnvironmentVariables()


Exception trace:
#0 ()
   vendor/symfony/process/ProcessBuilder.php:272
#1 Symfony\Component\Process\ProcessBuilder::getProcess()
   vendor/helhum/typo3-console/Classes/Mvc/Cli/CommandDispatcher.php:200
#2 Helhum\Typo3Console\Mvc\Cli\CommandDispatcher::executeCommand()
   vendor/helhum/typo3-console/Classes/Install/CliSetupRequestHandler.php:110
#3 Helhum\Typo3Console\Install\CliSetupRequestHandler::setup()
   vendor/typo3-console/composer-auto-setup/src/Composer/InstallerScript/SetupTypo3.php:101
#4 Typo3Console\ComposerAutoSetup\Composer\InstallerScript\SetupTypo3::run()
   vendor/typo3/cms-composer-installers/src/Plugin/Core/ScriptDispatcher.php:88
#5 TYPO3\CMS\Composer\Plugin\Core\ScriptDispatcher::executeScripts()
   vendor/typo3/cms-composer-installers/src/Plugin/PluginImplementation.php:93
#6 TYPO3\CMS\Composer\Plugin\PluginImplementation::postAutoloadDump()
   vendor/typo3/cms-composer-installers/src/Installer/Plugin.php:125
#7 TYPO3\CMS\Composer\Installer\Plugin::listen()
#8 call_user_func()
   phar:///home/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:171
#9 Composer\EventDispatcher\EventDispatcher::doDispatch()
   phar:///home/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:96
#10 Composer\EventDispatcher\EventDispatcher::dispatchScript()
   phar:///home/bin/composer.phar/src/Composer/Autoload/AutoloadGenerator.php:312
#11 Composer\Autoload\AutoloadGenerator::dump()
   phar:///home/bin/composer.phar/src/Composer/Installer.php:302
#12 Composer\Installer::run()
   phar:///home/bin/composer.phar/src/Composer/Command/UpdateCommand.php:161
#13 Composer\Command\UpdateCommand::execute()
   phar:///home/bin/composer.phar/vendor/symfony/console/Command/Command.php:242
#14 Symfony\Component\Console\Command\Command::run()
   phar:///home/bin/composer.phar/vendor/symfony/console/Application.php:842
#15 Symfony\Component\Console\Application::doRunCommand()
   phar:///home/bin/composer.phar/vendor/symfony/console/Application.php:193
#16 Symfony\Component\Console\Application::doRun()
   phar:///home/bin/composer.phar/src/Composer/Console/Application.php:251
#17 Composer\Console\Application::doRun()
   phar:///home/bin/composer.phar/vendor/symfony/console/Application.php:117
#18 Symfony\Component\Console\Application::run()
   phar:///home/bin/composer.phar/src/Composer/Console/Application.php:100
#19 Composer\Console\Application::run()
   phar:///home/bin/composer.phar/bin/composer:58
#20 require()
   /home/bin/composer.phar:24
```

**Comment by helhum** [comment]
ok, thanks. Fix is now merged in console, as I could reproduce (and finally fix) it.

**Comment by helipus** [comment]
Thanks a lot with the patch  cbfbf5ba3c86b03b6b28f3545066e511e19e9a1f it is working now!
